/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'maheshvibhute' at '10/6/17 5:21 PM' with Gradle 2.11
 *
 * @author maheshvibhute, @date 10/6/17 5:21 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
